### ISSUE TITLE
/setspawnpos오류

### ISSUE THREAD

**Issue by bugking12** [HelloWorld017/ZombieGame#4]
좀비게임을실행하려고서버에들어가서/setspawnpos를쳤는데아무것도일어나지않으며적정인원이되어도실행이되지않습니다

**Comment by HelloWorld017** [comment]
로그도 같이 올려주실 수 있으신가요?

**Comment by ruddn0101** [comment]
개인적의로 밑에 좀비인지 인간인지 자신정보보여주고 라운드가 끝나면 다시 월래스폰지점의로 모이게 해주면 좋켓네요

**Comment by HelloWorld017** [comment]
좀비인지 인간인지 보여주는 것은 원래 게임 규칙상 하지 않습니다. 자신의 정보라 하더라도 게임 시작시에만 알 수 있기 때문에 그것을 밑에 써 넣는 것은 게임이 진행됨에 따라 필요가 없어지죠. 따라서 넣지 않았고요, 라운드가 끝났을 때 스폰지점으로 다시 모이게 하는 것은 구현하겠습니다.

추가: 죄송하지만 한 이슈에는 하나의 내용만 써주시면 감사하겠습니다.
