### ISSUE TITLE
Russian translate.

### ISSUE THREAD

**Issue by MrDoni98** [HelloWorld017/ZombieGame#7]
## If you want to add the Russian translation, so I use this.

WELCOME_MESSAGE: Добро пожаловать %s1, на Зомби Игра !
PLAYER_COUNT: Сейчас %s1 игроков !
WAIT_MESSAGE: Ждите остальных игроков! (%s1 сейчас)
SPAWNPOS_SET: Spawnpos установлен!
UNKNOWN_COMMAND: Неверная команда!
MUST_INGAME: Введите в игре!
PLAYER_LEAVE: Игрок %s1 вышел с игры!
WAS_INITIAL_ZOMBIE: Игрок %s1 стал первым zombie.!
NO_TOUCH_INFECTION: Игрок %s1 был заражен, потому что игрок не коснуться ни одного игрока за раунд .
ARE_INITIAL_ZOMBIE: Вы первый зомби! Атакуйте других чтобы заразить!
ARE_INITIAL_HUMAN: Вы первый человек! Избегайте зомби!
POPUP_WAITING_PLAYERS: §r§2Ждите игроков (%s1/%s2)...
POPUP_STATUS_ROUND: Раунд %s1
POPUP_STATUS_ROUND_REST: Перерыв (Раунд %s1)
POPUP_STATUS_PREPARATION: Подготовка в процессе ...
POPUP_STATUS_LEFT: 'Времени %s1m %s2s осталось'
ROUND_FINISHED: Раунд %s1 окончен!
ROUND_FINISHED_COUNT: 'Зомби: %s1, Люди: %s2'
ROUND_STARTED: Раунд %s1 начался!
WELCOME_GAME_MESSAGE: Добро пожаловать на Зомби батл.
GAME_EXPLANATION_1: Перед началом игры,% S1 начальные зомби будут выбраны.
GAME_EXPLANATION_2: Все знают, кто они, но они не знают, кто другие.
GAME_EXPLANATION_3: Игра имеет %s1 раундов. Если вы не трогайте, по крайней мере один раз за раунд, вы будете зомби.
GAME_EXPLANATION_4: После окончания раунда, количество зомби и человека будет уведомление.
GAME_EXPLANATION_5: Вы не можете коснуться, кто вы коснулись уже. Вы можете коснуться, нажав на другого игрока.
GAME_EXPLANATION_P2_1: |
  Когда вы с кем-то прикоснуться, результат
  Zombie-Zombie: Ничего.
  Zombie-Human: Человек станет зомби.
  Human-Human: Люди получите счет.
GAME_EXPLANATION_P2_2: После окончания игры, если все зомби, начальная зомби победит.
GAME_EXPLANATION_P2_3: Если один или более человек (ей) существует (ы), люди), который (есть) высокий балл победит.
GAME_EXPLANATION_P3_1: Когда игра начинается, вы получите лекарство.
GAME_EXPLANATION_P3_2: Если вы пьете лекарства в %s1 после заражения, вы станете человек, крое тех кто был изначально зомби.
GAME_FINISHED_ZOMBIE: 'Игра закончилась. Победитель: %s1, он зомби'
GAME_FINISHED_HUMAN: Игра окончена. Победил %s1 он был человеком и получил %s2 баллов
TOUCH_ALREADY_TOUCHED: Уже тронут!
PREPARATION_OR_REST: Раунд еще не начался!
MEDICINE_USED: Вы использовали лекарство!
...

**Comment by HelloWorld017** [comment]
Thank you for translating to Russian!

**Comment by MrDoni98** [comment]
I just found a mistake in my translation.Please fix it
GAME_EXPLANATION_P2_3: Если останется один или более человек , победит тот у кого больше баллов
